export const INCRIMENT_PAGE = "INCRIMENT_PAGE" 
export const SET_TOTAL_PAGES = "SET_TOTAL_PAGES"

export const SET_MOVIES = "SET_MOVIES"
export const ADD_MOVIES = "ADD_MOVIES"

export const SET_CONFIG_SORTING = "SET_CONFIG_SORTING"
export const SET_CONFIG_GENRES = "SET_CONFIG_GENRES"

export const SET_OPTION_GENRES = "SET_OPTION_GENRES"

export const CLEAR_MOVIES = "CLEAR_MOVIES"

export const REMOVE_MOVIE = "REMOVE_MOVIE"
export const SET_MOVIE = "SET_MOVIE"

export const REMOVE_FAVORITE = "REMOVE_FAVORITE"
export const ADD_FAVORITE = "ADD_FAVORITE"

export const DEFAULT = "DEFAULT"